### ISSUE TITLE
Optimize Performance

### ISSUE THREAD

**Issue by snakefoot** [BrutalHack/NLog-Example#1]
Performing Path.GetFileName for every logevent is very expensive. Instead cache the Logger in dictionary with `callerFilePath` as key.

https://github.com/BrutalHack/NLog-Example/blob/0af7829c4c8a5b2d0390e382f21128426cd0bb47/Assets/Scripts/CustomLogger.cs#L111

Remember to protect with a `lock (_dictionary)` or use `ConcurrentDictionary`

**Comment by Benjamin-Justice** [comment]
Thank you for pointing this out.
I just implemented it and tested for performance (10.000 log messages, measuring timespan in code):

With cached Logger by callerFilePath:
8,146s
8,168s
8,144s

Without cached logger (NLog caches the logger itself, so we only save the time required for Path.GetFileName)
8,142s
8,164s
8,114s

I would have actually expected to see a difference.
There could also be a noticeable performance difference on some platforms like Android/iOS/Nintendo 3DS.

Introduced in https://github.com/BrutalHack/NLog-Example/commit/e41469eb6d9b6de26c7187f571a09a3bd66f6a9d

**Comment by snakefoot** [comment]
That is terrible performance. Please make sure to use KeepFileOpen=true and ConcurrentWrites=false for the file-target.

**Comment by snakefoot** [comment]
Instead of using two lookups with ContainsKey, then you should use TryGetValue (single lookup)

**Comment by Benjamin-Justice** [comment]
I am still new to NLog, so I missed KeepFileOpen and Concurrent writes, thanks.

I was in a train, so my computer was running on energy saving mode.
At home I get 4,1s. 
Please keep in mind, that I have the Unity Engines console as a second target, which is very slow.
However, it is the normal workflow Unity developers are used to and many would miss it.

Without Unity console target:
1,2s without KeepFileOpen
0,4s with KeepFileOpen and ConcurrentWrites

Now I'm at around 3,4s for 10k messages to Unity Console and File Target

**Comment by snakefoot** [comment]
If a target is very slow. Then one can try and create NLog AsyncTargetWrapper for the slow target. (Remember to configure TimeToSleepBetweenBatches=0 or else it will generate timer-triggers even when idle, this will be changed with NLog ver. 4.6).

**Comment by snakefoot** [comment]
Try to implement the code like this:

```c#
    private static Logger GetLogger(string callerFilePath)
    {
        if (!Loggers.TryGetValue(callerFilePath, out Logger logger))
        {
            logger = LogManager.GetLogger(Path.GetFileName(callerFilePath));
            Loggers[callerFilePath] = logger;
        }
        return logger;
    }
```

**Comment by Benjamin-Justice** [comment]
Wow, guess I was too tired to code. Thanks for pointing that out.

**Comment by snakefoot** [comment]
@zanval One last thing you could try, would be changing this:

```c#
config.AddRuleForAllLevels(logUnity);
```

Into this:

```c#
config.AddRuleForAllLevels(new NLog.Targets.Wrappers.AsyncTargetWrapper(logUnity) { TimeToSleepBetweenBatches = 0 });
```

P.S. With NLog 4.6 then TimeToSleepBetweenBatches will default to 1, so it no longer has to be configured explicitly.
